redis:
  image: redis
  command: redis-server --appendonly yes
  volumes:
    - /opt/redis/data:/data
  restart: always
# mongo:
#   image: mongo
#   command: --smallfiles
#   volumes:
#     - /opt/mongo/data/db:/data/db
#   restart: always
mshard:
  image: ermaker/mshard_server
  links:
    - redis
  env_file: .env.mshard
  environment:
    - VIRTUAL_HOST=mshard.ermaker.tk
  restart: always
# honeypot:
#   image: ermaker/honeypot
#   links:
#     - mongo
#     - mshard
#   env_file: .env.honeypot
#   environment:
#     - VIRTUAL_HOST=honeypot.ermaker.tk
#     - RAILS_ENV=production
#     - MONGO_DATABASE=honeypot_production
#     - WEB_CONCURRENCY=4
#   restart: always
nginx:
  image: nginx
  volumes:
    - ./html/:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=ermaker.tk
  restart: always
nginx-proxy:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
    - '80:80'
  restart: always
fluentd:
  image: ermaker/fluentd
  env_file: .env.fluentd
  volumes:
    - ./fluentd/td-agent.conf:/etc/td-agent/td-agent.conf:ro
    - /var/lib/docker:/var/lib/docker
  restart: always
